services:
  db:
    image: postgres:16
    container_name: songlist_db
    env_file:
      - ./backend/.env   
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data


volumes:
  dbdata:
